name: 'PyPoetry'
author: '@hericlesme'
description: 'An Action for python dependency management and packaging with Poetry'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  command:
    description: 'The poetry command to run'
    required: true
  python_version:
    description: 'The python version to install'
    required: false
    default: '3.8'
  poetry_version:
    description: 'The poetry version to install'
    required: false
    default: '1.0'
  workdir:
    description: 'Sets the working directory for poetry'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
